version: '3'
services:
  postgres:
    image: postgres:15.6-alpine
    container_name: postgres
    restart: always
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: tiger_kittens
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
  tiger-kittens:
    image: tiger-kittens:latest
    container_name: tiger-kittens-api
    restart: always
    ports:
      - "9000:9000"
    environment:
      ENV: local
      SQL_HOST: postgres
  tiger-kittens-migrate:
    image: tiger-kittens:latest
    container_name: tiger-kittens-migration
    environment:
      ENV: local
      SQL_HOST: postgres
    command: ./tiger-kittens db:migrate
  tiger-kittens-seed:
    image: tiger-kittens:latest
    container_name: tiger-kittens-seeder
    environment:
      ENV: local
      SQL_HOST: postgres
    command: ./tiger-kittens db:seed