// Code generated by mockery v2.36.0. DO NOT EDIT.

package mock

import (
	mock "github.com/stretchr/testify/mock"
	mailqueue "github.com/vekaputra/tiger-kittens/internal/helper/mailqueue"
)

// Provider is an autogenerated mock type for the Provider type
type Provider struct {
	mock.Mock
}

// Add provides a mock function with given fields: job
func (_m *Provider) Add(job mailqueue.SendEmailJob) {
	_m.Called(job)
}

// NewProvider creates a new instance of Provider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *Provider {
	mock := &Provider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
